
server:
  port: 6060

spring:
  application:
    name: keyswap
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
       hibernate:
        show_sql: false
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    platform: POSTGRESQL
    url: jdbc:postgresql://${RDS_HOSTNAME:127.0.0.1}:5432/keyswap
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

jwt-secret: ${JWT_SECRET:abbb766d-dd23-45d3-af40-83db9d4dbbf4}
