
server:
  port: 5000
  compression:
    enabled: true
    mime-types: application/json
  tomcat:
    connection-timeout:

spring:
  application:
    name: keyswap
  profiles:
    active: nocommit,generated,${ENV:dev}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
       hibernate:
        show_sql: false
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: POSTGRESQL
    url: jdbc:postgresql://${RDS_HOSTNAME:127.0.0.1}:5432/${RDS_DB_NAME:keyswap}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  mail:
    host: email-smtp.us-west-2.amazonaws.com
    username: AKIAI7543AJ4RKGUYHBA
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          connectiontimeout: 10000
          timeout: 5000
          writetimeout: 10000
          starttls:
            enable: true
            required: true

env: ${ENV:dev}
