
server:
  port: 5000

spring:
  application:
    name: keyswap
  profiles:
    active: nocommit,${ENV:dev}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
       hibernate:
        show_sql: false
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
  datasource:
    platform: POSTGRESQL
    url: jdbc:postgresql://${RDS_HOSTNAME:127.0.0.1}:5432/keyswap
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  mail:
    host: email-smtp.us-west-2.amazonaws.com
    username: AKIAI7543AJ4RKGUYHBA
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          connectiontimeout: 10000
          timeout: 5000
          writetimeout: 10000
          starttls:
            enable: true
            required: true

jwt-secret: ${JWT_SECRET:abbb766d-dd23-45d3-af40-83db9d4dbbf4}
env: ${ENV:dev}
