export enum UserSort {
    USER_NAME = "USER_NAME",
    RATING = "RATING",
    DECK_COUNT = "DECK_COUNT",
    PATRON_LEVEL = "PATRON_LEVEL",
    SAS_AVERAGE = "SAS_AVERAGE",
    TOP_SAS = "TOP_SAS",
    LOW_SAS = "LOW_SAS",
    TOTAL_POWER = "TOTAL_POWER",
    TOTAL_CHAINS = "TOTAL_CHAINS",
    FOR_SALE_COUNT = "FOR_SALE_COUNT"
}
